#!/bin/bash

NAME="git"
DESC="Git is a free and open source distributed version control system."
VERSION="1.7.10.3"
DIR="/tmp/fpm-build/$NAME-$VERSION"
INSTALL_DIR="$DIR/install"

if [ ! -d "$INSTALL_DIR" ]; then
  echo "Building..."
  mkdir -p $DIR
  cd $DIR
  wget http://git-core.googlecode.com/files/git-1.7.10.3.tar.gz
  tar -zxf git-1.7.10.3.tar.gz
  cd git-1.7.10.3
  ./configure --prefix=/usr --without-tcltk
  make
  make install DESTDIR=$INSTALL_DIR
fi

if [ -d "$INSTALL_DIR" ]; then
  echo "Build dir exists, making package..."
  cd $INSTALL_DIR
  fpm -s dir \
      -t deb \
      --name "$NAME" \
      --description "$DESC" \
      --version $VERSION \
      --depends "libssl0.9.8 (>=0)" \
      usr
fi